[package]
name = "mime_typed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime = { version = "0.3.16", optional = true }

[dev-dependencies]
mime = "0.3.16"

[features]
mime = ["dep:mime"]